spring:
  application:
    name: poker-stats-backend
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/pokerstats
    username: pokerstats
    password: pokerstats
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.pokerstats: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: changeme-this-is-a-development-secret-key-only
  expiration: 86400000  # 24 hours
  refresh-expiration: 604800000  # 7 days

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5433/pokerstats_test
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    redis:
      host: localhost
      port: 6380

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: ${PORT:8080}

logging:
  level:
    com.pokerstats: INFO
    org.springframework: INFO
    org.hibernate: INFO
  pattern:
    console: '{"timestamp": "%d{yyyy-MM-dd HH:mm:ss.SSS}", "level": "%-5level", "logger": "%logger{36}", "message": "%msg"}%n'

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
