# Alert rules for Poker Stats application

groups:
  - name: pokerstats_application
    interval: 30s
    rules:
      # Backend application alerts
      - alert: BackendDown
        expr: up{job="pokerstats-backend"} == 0
        for: 2m
        labels:
          severity: critical
          component: backend
        annotations:
          summary: "Backend application is down"
          description: "The Poker Stats backend application has been down for more than 2 minutes."

      - alert: BackendHighErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          component: backend
        annotations:
          summary: "High error rate in backend"
          description: "Backend is experiencing {{ $value | humanizePercentage }} error rate."

      - alert: BackendSlowResponses
        expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
          component: backend
        annotations:
          summary: "Backend response time is slow"
          description: "95th percentile response time is {{ $value }}s."

      # Database alerts
      - alert: DatabaseDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "PostgreSQL database is down"
          description: "The PostgreSQL database has been unreachable for more than 1 minute."

      - alert: DatabaseHighConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "Database is using {{ $value | humanizePercentage }} of available connections."

      # Redis alerts
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 2m
        labels:
          severity: warning
          component: cache
        annotations:
          summary: "Redis cache is down"
          description: "Redis has been down for more than 2 minutes. Application will still work but performance may degrade."

      - alert: RedisHighMemory
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          component: cache
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis is using {{ $value | humanizePercentage }} of allocated memory."

      # System resource alerts
      - alert: HighCPUUsage
        expr: process_cpu_usage > 0.8
        for: 10m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage has been above 80% for 10 minutes."

      - alert: HighMemoryUsage
        expr: jvm_memory_used_bytes / jvm_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          component: backend
        annotations:
          summary: "High JVM memory usage"
          description: "JVM is using {{ $value | humanizePercentage }} of allocated memory."

      - alert: DiskSpaceLow
        expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} < 0.1
        for: 5m
        labels:
          severity: critical
          component: system
        annotations:
          summary: "Disk space is running low"
          description: "Less than 10% disk space remaining on root partition."

      # Application-specific alerts
      - alert: NoRecentSessions
        expr: increase(sessions_created_total[24h]) == 0
        for: 48h
        labels:
          severity: info
          component: application
        annotations:
          summary: "No game sessions logged recently"
          description: "No new sessions have been logged in the past 48 hours. This might be normal."

      - alert: HighFailedLogins
        expr: increase(auth_login_failed_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          component: security
        annotations:
          summary: "High number of failed login attempts"
          description: "More than 10 failed login attempts in the last 5 minutes. Possible brute force attack."
